application: oculusunrift
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  static_files: static/start.html
  upload: static/start.html
  secure: always

- url: /
  static_dir: static
  secure: always
